[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.20.4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200