services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    nodeVersion: 22.16.0
    buildCommand: npm install && npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
